# Generated by Django 2.1.5 on 2019-01-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('temp', models.FloatField(default=0.0)),
                ('summary', models.CharField(max_length=50)),
                ('search_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
