# Generated by Django 2.1.5 on 2019-01-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
