# Generated by Django 2.1.5 on 2019-01-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop19', '0002_auto_20190128_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
    ]
