# Generated by Django 2.1.5 on 2019-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('debut', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(default='No description yet...')),
            ],
        ),
    ]
