# Generated by Django 2.1.7 on 2019-04-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
